weights: yolov5s.pt
cfg: /home/zzx/code/2D/yolo/single_pixel_yolov5-6/models/yolov5s_sp.yaml
data: data/NPS-Drone.yaml
hyp: data/hyps/hyp.scratch.yaml
epochs: 15
batch_size: 1
imgsz: 640
rect: false
resume: false
nosave: false
noval: false
noautoanchor: false
evolve: null
bucket: ''
cache: null
image_weights: false
device: ''
multi_scale: false
single_cls: false
adam: false
sync_bn: false
workers: 9
project: runs/train/visdrone
name: exp
exist_ok: true
quad: false
linear_lr: false
label_smoothing: 0.0
patience: 100
freeze: 0
save_period: -1
local_rank: -1
entity: null
upload_dataset: false
bbox_interval: -1
artifact_alias: latest
save_dir: runs/train/visdrone/exp
